name: Unit Tests CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test --all-features --all-targets --verbose
